---
# Slightly advanced package installation
- name: Basic Package Installation
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    - package_basic: "no"
    - install_vim: "no"
    - uninstall_vim: "no"
    - Package_Suite_Install_Using_Vars: "no"
    - Package_Suite_Install_Using_Items: "no"
    - install_apache: "yes"
    - uninstall_apache: "no"
    - files_role: "no"

  roles:
    - Package-Basic
